wget https://www.dfam.org/releases/current/families/FamDB/README.txt
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.0.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.1.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.2.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.3.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.4.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.5.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.6.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.7.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.8.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.9.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.10.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.11.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.12.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.13.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.14.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.15.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.16.h5.gz
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.0.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.1.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.2.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.3.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.4.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.5.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.6.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.7.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.8.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.9.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.10.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.11.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.12.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.13.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.14.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.15.h5.gz.md5
wget https://www.dfam.org/releases/current/families/FamDB/dfam39_full.16.h5.gz.md5
